export const egyptCities = [
  "Cairo",
  "Alexandria",
  "Giza",
  "Shubra El-Kheima",
  "Port Said",
  "Suez",
  "Luxor",
  "Mansoura",
  "El-Mahalla El-Kubra",
  "Tanta",
  "Asyut",
  "Ismailia",
  "Fayyum",
  "Zagazig",
  "Aswan",
  "Damietta",
  "Damanhur",
  "El-Minya",
  "Beni Suef",
  "Hurghada",
  "Qena",
  "Sohag",
  "Shibin El Kom",
  "Banha",
  "Kafr El Sheikh",
  "Arish",
  "Mallawi",
  "Al-Minya",
  "Shibin El Qanater",
  "El-Gamalia",
  "El-Qantara",
  "Qalyub",
  "Ras El Bar",
  "Rafah",
  "Ras Gharib",
  "Ras Sedr",
  "Sadat",
  "Sallum",
  "Safaga",
  "Saint Catherine",
  "Saint Mark",
  "El Senbellawein",
  "Sharm El Sheikh",
  "Sheikh Zayed City",
  "Tama al-Amdid",
  "Tarabin",
  "Tukh",
  "Dahab",
  "Fuwah",
  "Kafr El Dawwar",
  "Salah Salem",
  "Shirbin",
  "Sidi Barrani",
  "Sidi Salem",
  "Sohag",
  "Dahshur",
  "Fayid",
  "Kharga",
  "Nag Hammadi",
  "Nuweiba",
  "Ras El Bar",
  "Salum",
  "Siwa",
];
